// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_query.sql

package repository

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    id, name
) VALUES (?, ?)
RETURNING id, name, created_at
`

type CreateRoomParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.ID, arg.Name)
	var i Room
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
;

delete from rooms where id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getAllRooms = `-- name: GetAllRooms :many
SELECT id, name, created_at FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) GetAllRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, created_at FROM rooms
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :exec
;

update rooms
set name = ?
where id = ?
`

type UpdateRoomParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom, arg.Name, arg.ID)
	return err
}
