// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package rplatform

import (
	"database/sql"
)

type Message struct {
	ID        string
	RoomID    string
	UserID    string
	Content   string
	CreatedAt sql.NullTime
}

type Room struct {
	ID        string
	Name      string
	CreatedAt sql.NullTime
}

type RoomUser struct {
	RoomID   string
	UserID   string
	JoinedAt sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
